### ISSUE TITLE
Errors on Sleep Data

### ISSUE THREAD

**Issue by esmoyer** [stratus-ss/garmin-influxdb#3] opened 2023-09-18 19:25 UTC
Anyone else getting errors for the last month or so?

```
DEBUG:garminconnect:Requesting steps data
DEBUG:garminconnect:URL: https://connect.garmin.com/modern/proxy/wellness-service/wellness/dailySummaryChart/a1992e4a-dba6-4e52-8385-XXXXX
DEBUG:garminconnect:Headers: {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0', 'NK': 'NT'}
DEBUG:urllib3.connectionpool:https://connect.garmin.com:443 "GET /modern/proxy/wellness-service/wellness/dailySummaryChart/a1992e4a-dba6-4e52-8385-XXXXX?date=2023-9-17 HTTP/1.1" 200 None
DEBUG:garminconnect:Requesting user summary
DEBUG:garminconnect:URL: https://connect.garmin.com/modern/proxy/usersummary-service/usersummary/daily/a1992e4a-dba6-4e52-8385-XXXXX
DEBUG:garminconnect:Headers: {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0', 'NK': 'NT'}
DEBUG:urllib3.connectionpool:https://connect.garmin.com:443 "GET /modern/proxy/usersummary-service/usersummary/daily/a1992e4a-dba6-4e52-8385-XXXXX?calendarDate=2023-9-17 HTTP/1.1" 200 None
DEBUG:garminconnect:Requesting sleep data
DEBUG:garminconnect:URL: https://connect.garmin.com/modern/proxy/wellness-service/wellness/dailySleepData/a1992e4a-dba6-4e52-8385-XXXXX
DEBUG:garminconnect:Headers: {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0', 'NK': 'NT'}
DEBUG:urllib3.connectionpool:https://connect.garmin.com:443 "GET /modern/proxy/wellness-service/wellness/dailySleepData/a1992e4a-dba6-4e52-8385-XXXXX?date=2023-9-17&nonSleepBufferMinutes=60 HTTP/1.1" 404 None
'NoneType' object has no attribute 'json'
Unknown error occurred during Garmin Connect Client get sleep_data
```

**Comment by stratus-ss** [comment] 2023-09-18 19:30
I'll have to look into this, seems to imply they moved the path for the wellness service (potentially)

**Comment by esmoyer** [comment] 2023-09-18 19:34
Wow, thanks for the quick response. I was just starting to try and search for their API docs to see if that was the case. For now I was able to comment out the sleep stuff and it seems to be going for now. Thanks!

EDIT: Whoops, didn't mean to click close!

**Comment by stijnh92** [comment] 2023-09-18 19:56
I am having the exact same issue

**Comment by stratus-ss** [comment] 2023-09-18 20:27
Digging into it, its not a problem on my side. I dumped the client information that returns

[Line 228](https://github.com/stratus-ss/garmin-influxdb/blob/c165628f21139d2e9240658f42e6c9d4c78cf8e5/garmin-to-influxdb.py#L228C12-L228C12) simply creates a connection and gets bunch a bunch of stuff from Garmin

In this list I can see the following
![image](https://github.com/stratus-ss/garmin-influxdb/assets/8162705/b8900497-3e3d-4710-bcbf-30a4996a2366)
![image](https://github.com/stratus-ss/garmin-influxdb/assets/8162705/02cab757-7e49-4999-b93d-759b6cfb8afc)

This indicates the 404 is coming from either them not updating the client information, or them having some infra problem.

As I don't have access to their API docs, I have to rely on what the Garmin returns to me when I establish a client connection. At this point the only thing to do is comment out the sleep section and try again later to see if the issue persists

You want to comment these lines out:

```
    # client_get_sleep = 'client.get_sleep_data("%s")' % date_without_leading_zero
```
```
    # sleep_data = get_data_from_garmin("sleep_data", client_get_sleep, client=client)
    # sleep_data_date = time.mktime(time.strptime(sleep_data['dailySleepDTO']['calendarDate'], garmin_date_format))
```

```
    # useful_daily_sleep_data = {
    #     'awake_minutes': sleep_data['dailySleepDTO']['awakeSleepSeconds'],
    #     'light_sleep_minutes': sleep_data['dailySleepDTO']['lightSleepSeconds'],
    #     'deep_sleep_minutes': sleep_data['dailySleepDTO']['deepSleepSeconds'],
    #     'total_sleep_minutes': sleep_data['dailySleepDTO']['sleepTimeSeconds'],
    #     'current_date': time.strftime(influxdb_time_format, time.localtime(sleep_data_date))
    #  
```
```
    # create_influxdb_daily_measurement(useful_daily_sleep_data, influxdb_client)

```

**Comment by esmoyer** [comment] 2023-09-18 20:33
Thanks @stratus-ss. When I try things in Postman, I get this...not sure if it means anything or not:
![image](https://github.com/stratus-ss/garmin-influxdb/assets/17444085/3536a265-c4b7-431d-831f-2dfac4800097)

I have also been digging into the GarminConnect repo and am not seeing anything crazy different other than they appear to be using Garth now for Auth. Going to try and do some more digging to see what else I can find.

**Comment by esmoyer** [comment] 2023-09-18 20:41
Would the JSON error mean anything? Maybe they format the data different now? 

When I look at my data it appears this started sometime after 8/22/2023 at 7pm central...really strange

**Comment by stratus-ss** [comment] 2023-09-18 20:46
The json error is because I am making the assumption that the resource exists. The client object returns from the Garmin backend and I should do some error checking but I just take what I get and run some parsing against the supposed object. It has a type of NONE I _believe_ because of the 404 error. So the json error is being barfed up by me not doing error checking

**Comment by esmoyer** [comment] 2023-09-19 00:31
From what I can tell, it might have something to do with the changes python-garminconnect has made over the last month; but granted I am definitely no expert. Not sure if that is actually the case or not.

**Comment by stijnh92** [comment] 2023-09-19 07:16
I am still able to retrieve the sleep data from the example.py file of https://github.com/cyberjunky/python-garminconnect

**Comment by esmoyer** [comment] 2023-09-19 11:54
> I am still able to retrieve the sleep data from the example.py file of https://github.com/cyberjunky/python-garminconnect

So am I. Which is why I am wondering if something in this repo needs to be updated to work with what they changed? But I could be completely off on that.

**Comment by stratus-ss** [comment] 2023-09-19 14:35
I found the problem. Thanks for the help.

The issue is, in fact, on the Garmin side... insofaras they changed something. Previously, they were not taking ISO formatted date like 2023-09-19, and instead were ONLY taking 2023-9-19, this program was removing the leading zero

At least in my quick test, removing the function that was stripping the zero out of the date, seems to have resolved the issue. I am going to run a longer date range and see what happens. 

It's also hard to know if this change effects historical data... i.e. did their system retrofit this change going forward from a point or does it include the data that I had to implement the workaround for in the first place

**Comment by stratus-ss** [comment] 2023-09-19 14:46
I pushed a fix. I tested it on data from Sept 1 to 17. 

#itWorksOnMyMachine

If folks could test and confirm that would be great

**Comment by stijnh92** [comment] 2023-09-19 14:51
Yes that works on my machine as well 😀 thanks for investigating this issue!

**Comment by stratus-ss** [comment] 2023-09-19 14:57
feel free to reopen if there is more attention required

**Closed as completed by stratus-ss** 2023-09-19 14:57 UTC

**Comment by esmoyer** [comment] 2023-09-23 19:39
Not sure why I didn't get notifications on this, but wanted to say THANK YOU and it's working!
